### ndim, shape, size, dtype, itemsize, nbytes

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim) # number of dimensions
print("x3 shape:", x3.shape) # size of each dimension
print("x3 size: ", x3.size)
print("dtype:", x3.dtype) # data type
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes") # total size : itemsize * size

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


Unlike Python lists, NumPy arrays have a fixed type. If you attempt to insert a floating-point value to an integer array, the value will be silently truncated.

### arange

In [2]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
np.arange(10)[5::-2]

array([5, 3, 1])

In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [6]:
x2[:3, ::2]  # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [7]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [8]:
#x2[:, 0] # first col
#x2[0, :] # first row or # x2[0]

In [9]:
# Array slices return views rather than copies of the array data.
print(x2)

x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### copy, reshape, newaxis
### concatenate
### np.vstack (vertical stack) and np.hstack (horizontal stack)
### np.dstack will stack arrays along the third axis

In [10]:
# or we can use
x2_sub_copy = x2[:2, :2].copy()

In [11]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.array([1, 2, 3])[np.newaxis, :] # .reshape((1, 3))

array([[1, 2, 3]])

In [13]:
np.array([1, 2, 3])[:, np.newaxis] # .reshape((3, 1))

array([[1],
       [2],
       [3]])

In [14]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [15]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid], axis=1) # concatenate along the second axis (zero-indexed)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [17]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### np.split, np.hsplit, and np.vsplit
### np.dsplit will split arrays along the third axis

In [18]:
# N split-points, leads to N + 1 subarrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [19]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
